#include "Docstrings.h"
namespace docstrings {

    std::string EHMNetNode() {
        return R"(EHMNetNode(layer: int, identity: Set[int])
A node in the :class:`~.EHMNet` constructed by :class:`~.EHM`.

Parameters
----------
layer: :class:`int`
    Index of the network layer in which the node is placed. Since a different layer in the network is built for
    each track, this also represented the index of the track this node relates to.
identity: :class:`set` of :class:`int`
    The identity of the node. As per Section 3.1 of [EHM1]_, "the identity for each node is an indication of how
    measurement assignments made for tracks already considered affect assignments for tracks remaining to be
    considered".
)";
    }

    std::string EHMNet()
    {
        return R"(EHMNet(root: EHMNetNode, validation_matrix: numpy.ndarray)
Represents the nets constructed by :class:`~.EHM`.

Parameters
----------
root: :class:`~.EHMNetNode`
    The net root node.
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
tree: :class:`~.EHMTree`
    The tree representing the net layers structure.
)";
    }

    std::string EHMNet___init__()
    {
        return R"(__init__(root: pyehm.net.EHMNetNode, validation_matrix: numpy.ndarray, tree: pyehm.net.EHMTree)";
    }

    std::string EHMNet_num_layers()
    {
        return R"(num_layers() -> int
Number of layers in the net)";
    }

    std::string EHMNet_num_nodes()
    {
        return R"(Number of nodes in the net)";
    }

    std::string EHMNet_root()
    {
        return R"(The root node of the net)";
    }

    std::string EHMNet_nodes()
    {
        return R"(The nodes comprising the net)";
    }

    std::string EHMNet_nodes_forward()
    {
        return R"(The net nodes, ordered by increasing layer)";
    }

    std::string EHMNet_add_node()
    {
        return R"(add_node(node: EHMNetNode, parent: EHMNetNode, detection: int)
Add a node to the network.

Parameters
----------
node: :class:`~.EHMNetNode`
    The node to be added.
parent: :class:`~.EHMNetNode`
    The parent of the node.
detection: :class:`int`
    Index of measurement representing the parent child relationship.
)";
    }

    std::string EHMNet_add_edge()
    {
        return R"(add_edge(parent: EHMNetNode, child: EHMNetNode, detection: int)
Add edge between two nodes, or update an already existing edge by adding the detection to it.

Parameters
----------
parent: :class:`~.EHMNetNode`
    The parent node, i.e. the source of the edge.
child: :class:`~.EHMNetNode`
    The child node, i.e. the target of the edge.
detection: :class:`int`
    Index of measurement representing the parent child relationship.
)";
    }

    std::string EHMTree()
    {
        return R"(EHMTree(track: int, children: List[EHMTree], detections: Set[int])
Represents the track tree structure generated by :func:`~pyehm.core.EHM2.construct_tree`.

The :class:`~.EHMTree` object represents both a tree as well as the root node in the tree.

Parameters
----------
track: :class:`int`
    The index of the track represented by the root node of the tree
children: :class:`list` of :class:`~.EHMTree`
    Sub-trees that are children of the current tree
detections: :class:`set` of :class:`int`
    Set of accumulated detections
)";
    }

    std::string EHMTree_depth()
    {
        return R"(The depth of the tree)";
    }

    std::string EHMTree_nodes()
    {
		return R"(The nodes in the tree)";
    }

    std::string Cluster()
    {
        return R"(Cluster(tracks: List[int], detections: List[int] = [], validation_matrix: numpy.ndarray = numpy.array([]), likelihood_matrix: numpy.ndarray = numpy.array([]))
A cluster of tracks sharing common detections.

Parameters
----------
tracks: :class:`list` of `int`
    Indices of tracks in cluster
detections: :class:`list` of `int`
    Indices of detections in cluster. Defaults to an empty list.
validation_matrix: :class:`numpy.ndarray`
    The validation matrix for tracks and detections in the cluster. Defaults to an empty array.
likelihood_matrix: :class:`numpy.ndarray`
    The likelihood matrix for tracks and detections in the cluster. Defaults to an empty array.
)";
    }

    std::string gen_clusters()
    {
        return R"(gen_clusters(validation_matrix: numpy.ndarray, likelihood_matrix: numpy.ndarray = numpy.array([])) -> List[Cluster]
Cluster tracks into groups sharing detections

Parameters
----------
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
likelihood_matrix: :class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the unnormalised
    likelihoods for all combinations of tracks and detections. The first column corresponds
    to the null hypothesis. Defaults to an empty array, in which case the likelihood matrices of
    the generated clusters will also be empty arrays.
)";
    }

    std::string EHM()
    {
        return R"(Efficient Hypothesis Management (EHM)

An implementation of the EHM algorithm, as documented in [EHM1]_.
)";
    }

    std::string EHM_construct_net()
    {
        return R"(construct_net(validation_matrix: numpy.ndarray) -> EHMNet
Construct the EHM net as per Section 3.1 of [EHM1]_

Parameters
----------
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).

Returns
-------
: :class:`~.EHMNet`
    The constructed net object
)";
    }

    std::string EHM_construct_tree()
    {
        return R"(construct_tree(validation_matrix: numpy.ndarray) -> EHMTree
Construct the EHM tree as per section 4.3 of [EHM2]_

Parameters
----------
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
Returns
-------
: :class:`~.EHMTree`
    The constructed tree object
)";
    }

    std::string EHM_compute_association_probabilities()
    {
        return R"(compute_association_probabilities(net: EHMNet, likelihood_matrix: numpy.ndarray) -> numpy.ndarray
Compute the joint association weights, as described in Section 3.3 of [EHM1]_

Parameters
----------
net: :class:`~.EHMNet`
    A net object representing the valid joint association hypotheses
likelihood_matrix: :class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the unnormalised
    likelihoods for all combinations of tracks and detections. The first column corresponds
    to the null hypothesis.

Returns
-------
:class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the normalised
    association probabilities for all combinations of tracks and detecrtons. The first
    column corresponds to the null hypothesis.
)";
    }

    std::string EHM_run()
    {
        return R"(run(validation_matrix: numpy.ndarray, likelihood_matrix: numpy.ndarray) -> numpy.ndarray
Run EHM to compute and return association probabilities

Parameters
----------
validation_matrix : :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
likelihood_matrix: :class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the unnormalised
    likelihoods for all combinations of tracks and detections. The first column corresponds
    to the null hypothesis.

Returns
-------
:class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the normalised
    association probabilities for all combinations of tracks and detections. The first
    column corresponds to the null hypothesis.
)";
    }

    std::string EHM2()
    {
        return R"(Efficient Hypothesis Management 2 (EHM2)

An implementation of the EHM2 algorithm, as documented in [EHM2]_.
)";
    }

    std::string EHM2_construct_net()
    {
        return R"(construct_net(validation_matrix: numpy.ndarray) -> EHMNet
Construct the EHM2 net as per Section 4 of [EHM2]_

Parameters
----------
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
Returns
-------
: :class:`~.EHMNet`
    The constructed net object
)";
    }

    std::string EHM2_construct_tree()
    {
        return R"(construct_tree(validation_matrix: numpy.ndarray) -> EHMTree
Construct the EHM2 tree as per section 4.3 of [EHM2]_

Parameters
----------
validation_matrix: :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
Returns
-------
: :class:`~.EHMTree`
    The constructed tree object
)";
    }

    std::string EHM2_compute_association_probabilities()
    {
        return R"(compute_association_probabilities(net: EHMNet, likelihood_matrix: numpy.ndarray) -> numpy.ndarray
Compute the joint association weights, as described in Section 4.2 of [EHM2]_

Parameters
----------
net: :class:`~.EHMNet`
    A net object representing the valid joint association hypotheses
likelihood_matrix: :class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the unnormalised
    likelihoods for all combinations of tracks and detections. The first column corresponds
    to the null hypothesis.
Returns
-------
:class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the normalised
    association probabilities for all combinations of tracks and detecrtons. The first
    column corresponds to the null hypothesis.
)";
    }

    std::string EHM2_run()
    {
        return R"(run(validation_matrix: numpy.ndarray, likelihood_matrix: numpy.ndarray) -> numpy.ndarray
Run EHM2 to compute and return association probabilities

Parameters
----------
validation_matrix : :class:`numpy.ndarray`
    An indicator matrix of shape (num_tracks, num_detections + 1) indicating the possible
    (aka. valid) associations between tracks and detections. The first column corresponds
    to the null hypothesis (hence contains all ones).
likelihood_matrix: :class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the unnormalised
    likelihoods for all combinations of tracks and detections. The first column corresponds
    to the null hypothesis.

Returns
-------
:class:`numpy.ndarray`
    A matrix of shape (num_tracks, num_detections + 1) containing the normalised
    association probabilities for all combinations of tracks and detections. The first
    column corresponds to the null hypothesis.
)";
    }


}